
matrix:
    include:
        #- os: osx
        #  osx_image: xcode6.4
        #  #yosemite
        - os: osx
          osx_image: xcode8
          #el_capitan
        - os: osx
          osx_image: xcode9.2
          #sierra
        - os: osx
          osx_image: xcode10
          #high_sierra

language: generic

cache:
    directories:
        - $HOME/.stack/
        - $HOME/.rvm/

install:
    - ./automation/travis-install.sh

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: ./automation/travis-deploy.sh
      on:
          tags: true

