
language: minimal

cache:
    directories:
        - $HOME/.stack/

install:
    - ./automation/travis-install.sh

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: echo "Pretend we're building bottles here."
      on:
          tags: true

jobs:
    include:

        - stage: test
          os: osx
          osx_image: xcode8
          # macOS 10.11 el_capitan

        - stage: test
          os: osx
          osx_image: xcode9.2
          # macOS 10.12 sierra

        - stage: test
          os: osx
          osx_image: xcode10
          # macOS 10.13 high_sierra

        - stage: "Now deploy!"
          os: linux
          sudo: false
          install: echo "nothing to install"
          script: hostname && pwd
          before_deploy:
              - echo "Travis before_deploy step (in the deploy stage) here."
              - pwd
              - hostname | tee deploy-preparation.txt
          deploy:
              provider: script
              script: echo "Pretend we're gathering and publishing bottles here." && cat deploy-preparation.txt
              skip_cleanup: true
