
matrix:
    include:
        - os: osx
          osx_image: xcode6.4
          env: OSX_VERSION_NAME=yosemite
        - os: osx
          osx_image: xcode8
          env: OSX_VERSION_NAME=el_capitan
        - os: osx
          osx_image: xcode8.3
          env: OSX_VERSION_NAME=sierra

language: generic

cache:
    directories:
        - $HOME/.stack/

install:
    - ./automation/hello-github.sh
    - brew list --verbose haskell-stack || brew install --verbose haskell-stack
    - stack --no-terminal setup
    - stack --no-terminal test --only-dependencies

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: ./automation/deploy.sh
      on:
          tags: true

