
matrix:
    include:
        - os: osx
          osx_image: xcode6.4
          env: OSX_VERSION_NAME=yosemite
        - os: osx
          osx_image: xcode8
          env: OSX_VERSION_NAME=el_capitan
        - os: osx
          osx_image: xcode8.3
          env: OSX_VERSION_NAME=sierra

language: generic

cache:
    directories:
        - $HOME/.stack/
        - $HOME/.rvm/

install:
    - ./automation/hello-travis.sh
    - ./automation/hello-github.sh

    - "which gpg2 || ( which gpg && brew upgrade gnupg ) || brew install gnupg"
    - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - travis_retry rvm get latest
    - rvm osx-ssl-certs update all  # https://github.com/rubygems/rubygems.org/issues/613
    - rvm install ruby-2.1.8
    - rvm use ruby-2.1.8
    - rvm osx-ssl-certs update all  # how about a second time?
    - travis_retry gem update --system   # https://stackoverflow.com/questions/10246023/
    - ./automation/hello-travis.sh
    - travis_retry gem install bundler
    - travis_retry bundle install

    - which stack || brew install --verbose haskell-stack
    - stack --no-terminal setup
    - stack --no-terminal test --only-dependencies

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: ./automation/deploy.sh
      on:
          tags: true

