
language: ruby
rvm:
    - 2.6.5

cache:
    directories:
        - $HOME/.stack/
        - .stack-work
        - $HOME/.rvm/
    timeout: 1000

jobs:
    include:

        #osx_image: xcode9.2 # macOS 10.12 sierra

        - stage: "Build and test"
          os: osx
          osx_image: xcode10 # macOS 10.13 high_sierra
          install:
              - ./automation/install-stack.sh
          script:
              - stack --no-terminal test

        - os: osx
          osx_image: xcode11.3 # macOS 10.14 Mojave
          install:
              - ./automation/install-stack.sh
          script:
              - stack --no-terminal test


        - stage: "Bottle and upload"
          os: osx
          osx_image: xcode10 # macOS 10.13 high_sierra
          install:
              - ./automation/install-homebrew-automation.sh
          script:
              - homebrew_automation.rb help
              - homebrew_automation.rb version
          deploy:
              provider: script
              script: ./automation/bottle-and-upload.sh
              on:
                  tags: true

        - os: osx
          osx_image: xcode11.3 # macOS 10.14 Mojave
          install:
              - ./automation/install-homebrew-automation.sh
          script:
              - homebrew_automation.rb help
              - homebrew_automation.rb version
          deploy:
              provider: script
              script: ./automation/bottle-and-upload.sh
              on:
                  tags: true


        - stage: "Hand over to Github Actions"
          os: linux
          install:
              - echo "We don't have new macOS 10.15 machines here at Travis, so we'll need Github for that."
              - ./automation/install-homebrew-automation.sh
          script:
              - echo "However, it doesn't harm for us to publish the two Bottles we've built."
              - echo "Github Actions is able to append their 10.15 bottle without wiping our Bottles."
          deploy:
              provider: script
              script:
                  - ./automation/gather-and-publish.sh
                  - ./automation/trigger-github-dispatch.sh trigger_ci_run
              on:
                tags: true
