
language: ruby

cache:
    directories:
        - $HOME/.stack/
        - .stack-work
        - $HOME/.rvm/
    timeout: 1000

jobs:
    include:

        - stage: "Bottle and upload"
          os: osx
          osx_image: xcode9.2 # macOS 10.12 sierra

          install:
              - ./automation/install-stack.sh
              - ./automation/install-homebrew-automation.sh
          script:
              - homebrew_automation.rb help
              - stack --no-terminal test
          deploy:
              provider: script
              script: ./automation/bottle-and-upload.sh
              skip_cleanup: true
              on:
                  tags: true


        - stage: "Bottle and upload"
          os: osx
          osx_image: xcode10 # macOS 10.13 high_sierra

          install:
              - ./automation/install-stack.sh
              - ./automation/install-homebrew-automation.sh
          script:
              - homebrew_automation.rb help
              - stack --no-terminal test
          deploy:
              provider: script
              script: ./automation/bottle-and-upload.sh
              skip_cleanup: true
              on:
                  tags: true


        - stage: "Publish bottles"
          os: linux
          sudo: false
          language: minimal
          install: echo "Nothing to install"
          script: echo "Nothing to test"
          deploy:
              provider: script
              script: ./automation/gather-and-publish.sh
              skip_cleanup: true
              on:
                tags: true
