
matrix:
    include:
        - os: osx
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode8
        - os: osx
          osx_image: xcode8.3

language: generic

cache:
    directories:
        - $HOME/.stack/

install:
    - ./automation/hello-github.sh
    - brew update --verbose
    - brew list --verbose haskell-stack || brew install --verbose haskell-stack
    - stack --no-terminal setup
    - stack --no-terminal test --only-dependencies

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: stack exec deploy-sdist-github -- hack-assembler.cabal
      on:
          tags: true

