
os: osx
osx_image: xcode6.4

language: generic

before_install:
    - brew update --verbose
    - brew list --verbose haskell-stack || brew install --verbose haskell-stack

install:
    # A "failure" in our dependencies should be an "error" for us.
    - stack --no-terminal setup
    - stack --no-terminal test --only-dependencies

script:
    # We count out own failures as such.
    - stack --no-terminal test
