
language: ruby

cache:
    directories:
        - $HOME/.stack/
        - $HOME/.rvm/

install:
    - ./automation/travis-install.sh

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: echo "Pretend we're building and uploading bottles here."
      on:
          tags: true

jobs:
    include:

        - stage: test
          os: osx
          osx_image: xcode8
          # macOS 10.11 el_capitan

        - stage: test
          os: osx
          osx_image: xcode9.2
          # macOS 10.12 sierra

        - stage: test
          os: osx
          osx_image: xcode10
          # macOS 10.13 high_sierra

        - stage: "Now deploy!"
          os: linux
          sudo: false
          install: echo "Nothing to install; binaries should already be on Bintray."
          script: echo "Nothing to test; binaries should already be on Bintray."
          deploy:
              provider: script
              script: echo "Pretend we're gathering and publishing bottles here."
              skip_cleanup: true
