
matrix:
    include:
        - os: osx
          osx_image: xcode6.4
          env: OSX_VERSION_NAME=yosemite
        - os: osx
          osx_image: xcode8
          env: OSX_VERSION_NAME=el_capitan
        - os: osx
          osx_image: xcode8.3
          env: OSX_VERSION_NAME=sierra

language: generic

cache:
    directories:
        - $HOME/.stack/
        - $HOME/.rvm/

install:
    - ./automation/hello-travis.sh
    - ./automation/hello-github.sh
    - rvm osx-ssl-certs update all  # https://github.com/rubygems/rubygems.org/issues/613
    - rvm install 2.4
    - rvm use 2.4
    - gem install bundler
    - ./automation/hello-travis.sh
    - bundle install
    - brew list haskell-stack 2> /dev/null || brew install --verbose haskell-stack
    - stack --no-terminal setup
    - stack --no-terminal test --only-dependencies

script:
    - stack --no-terminal test

deploy:
    - skip_cleanup: true
      provider: script
      script: ./automation/deploy.sh
      on:
          tags: true

