
os: osx
osx_image: xcode6.4

language: generic

cache:
    directories:
        - $HOME/.stack/

before_install:
    - brew update --verbose
    - brew list --verbose haskell-stack || brew install --verbose haskell-stack

install:
    # A "failure" in our dependencies should be an "error" for us.
    - stack --no-terminal setup
    - stack --no-terminal test --only-dependencies

script:
    # We count out own failures as such.
    - stack --no-terminal test

before_deploy:
    - stack sdist

deploy:
    - skip_cleanup: true
      provider: releases
      api_key: $EASONCXZ_GITHUB_OAUTH_TOKEN
      file: $(stack path --dist-dir)/hack-assembler-0.1.0.0.tar.gz
      on:
          tags: true


